### ISSUE TITLE
Selectors kunnen beknopter

### ISSUE THREAD

**Issue by MicheleNL** [dennis-van-bennekom/minor-css-opdracht-1#2]
Selectors kunnen misschien nog wel beknopter. Kijk of je het met minder lange selectoren ook af kunt, met het oog op specificity. Wanneer je elementen generiek styled kun je deze stylen makkelijker hergebruiken, handig!

**Comment by dennis-van-bennekom** [comment]
Dankjewel voor de tip! Ik heb een aantal classes toegevoegd die alle onderdelen wat duidelijker maken.
